### ISSUE TITLE
text under the votes 

### ISSUE THREAD

**Issue by spirineta** [AccentsResearchLab/GamifyPsycholinguisticsExperiments#10]
Can we add text below each of the heads, so that the subjects can always see what answers they correspond to?

**Comment by mecathcart** [comment]
yes, I'll do that when I fix the image map.  What would you like the text to say? Maybe something related to the spy theme??

**Comment by spirineta** [comment]
From 1 to 5, this should be:
- this person is clearly a native speaker of my dialect
- this person is probably a native speaker of my dialect
- I can't really tell
- this person is probably not a native speaker of my dialect
  -this person is clearly not a native speaker of my dialect

2 things:
1. I was talking to @cesine last night and we thought it would be nice
   if each dialect had a story/mission attached to it. This could be
   narrated on the front page, IN the native dialect (in Russian for the
   Russian English). Depending on what that is, we could modify these
   choices a little.  We were thinking that this could be a spy encounter
   on a bus, and the subject has to transmit top secret info to the other
2. they can only speak in English so as not to raise suspicion, so our
   subject needs to be SURE he's talking to someone from home and can
   only figure this out based on the accent. So the 5 choices could be
   related to that.
3. I read that for accentedness 1-9 scales are used - apparently they
   capture the differences better. I'm going to do a bit more reading on
   that, but there is a chance we add 4 more heads.

On Wed, Feb 8, 2012 at 7:23 AM, mecathcart
reply@reply.github.com
wrote:

**Comment by mecathcart** [comment]
that sounds awesome! But maybe I should hold off on adding the text until
we know what kind of scale we're going to use? Since the text is kind of
long, it'll take some tweaking to get the size and placement right.
M.E.

On Wed, Feb 8, 2012 at 9:41 AM, spirineta <
reply@reply.github.com

**Comment by spirineta** [comment]
My vote is for 5: clearly, probably, not sure, probably not, clearly not. We could add possibly and possibly not... What do you think could be an additional pair if we had 9 points on the scale?

**Comment by mecathcart** [comment]
Hi spirineta,
I had a meeting with cesine on Friday.  We are thinking of going live with
gamify next week!! I added text to some of the images, but cesine said that
you had other smileys you wanted to use.  Since I already added them to
git, it might be better if you emailed me the smileys and I can modify
those.

As for another pair....(just) maybe... maybe not?
M.E.

On Thu, Feb 9, 2012 at 1:07 PM, spirineta <
reply@reply.github.com

**Comment by spirineta** [comment]
Yayyyyy!

The problem with maybe/maybe not is that I don't really see them as
meaning something DIFFERENT, but I guess this shouldn't stop us from
adding extra levels since apparently many people do this on a 1-9
scale. This means I need to get 2 more heads ready, but please note
that as far as the other drawings are concerned (default, hover, and
click version), I have already added them to the repo and pushed to
master too, woohoooooooo!

2 at 11:00 AM, mecathcart
reply@reply.github.com
wrote:

**Comment by mecathcart** [comment]
ahh ok, those were the ones cesine was talking about.  Ok, well I added text
to the default ones, and if you like the look, I can go ahead and add the
text to the hover and click versions.

On Sat, Feb 11, 2012 at 11:11 AM, spirineta <
reply@reply.github.com

**Comment by cesine** [comment]
3b519e282bc481e13c39c80bae94d2b0f346685d used css to make text below
