### ISSUE TITLE
some changes in design

### ISSUE THREAD

**Issue by spirineta** [AccentsResearchLab/GamifyPsycholinguisticsExperiments#19]
add bodies to spies standing in front of doors

increase height for remote

fix letter color

add "bus # 7 to DESTINATION" on the body of the bus

**Comment by cesine** [comment]
spirineta changed the bus number, i changed the letter color and we turned the remote sideways. we still havent done the bodies but its really a detail. closing this issue since we dont plan on doing it for milestone one
