### ISSUE TITLE
implement blocks of 12

### ISSUE THREAD

**Issue by spirineta** [AccentsResearchLab/GamifyPsycholinguisticsExperiments#20]
The slider looks great! Some small things:
1. after 12 sentences the little guys start lighting up (I'm assuming this is not finished yet - we're waiting for the progress table)
2. on the slider, the little circle slides ALL the way onto the blue side, but NOT all the way onto the red one - can we make it symmetrical (either slide all the way or not all the way on both sides)?
3. If possible, the Next button should be closer to the remote, and maybe have a more explicit title, such as "Evaluation complete. Next."

What do you think? Thank you.

**Comment by cesine** [comment]
did you pull the most recent version?
i had some of the same thoughts this morning too.
