### ISSUE TITLE
PIE CHARTS

### ISSUE THREAD

**Issue by spirineta** [AccentsResearchLab/GamifyPsycholinguisticsExperiments#28]
1. add info as to what they are getting, color-coded (see issue on 12th stop changes) -- add explanations, color-coded, as follows:

--- % natives correctly identified
--- % natives correctly rejected

--- % non-natives correctly rejected
--- % non-natives incorrectly accepted as natives

(for each category the two add up to 100, so maybe we should just give one number?)
1. make pie charts cumulative - they get a new one with each round, while also being able to see old ones (potential problem is formatting if they play too many rounds - one possible solution: only show LAST 5 rounds?)

**Comment by trisapeace** [comment]
Good beginner's tutorial for D3: http://christopheviau.com/d3_tutorial/
