### ISSUE TITLE
Find the Russian speaking participants 

### ISSUE THREAD

**Issue by cesine** [AccentsResearchLab/GamifyPsycholinguisticsExperiments#49]

**Comment by hisakonog** [comment]
get the first vote for all participants who chose Russian.  >>  spreadsheet 
get soundcheck visit from Russian speaking countries  >>  same spreadsheet 
sort  by date/time then should be able to see alternating votes and soundcheck visits

**Comment by hisakonog** [comment]
moved to https://github.com/AccentsResearchLab/GamifyPsycholingData/issues/2
