### ISSUE TITLE
connect image map to the vote value

### ISSUE THREAD

**Issue by cesine** [AccentsResearchLab/GamifyPsycholinguisticsExperiments#8]
n

**Comment by cesine** [comment]
hi @mecathcart :) i changed it to send the number rather than the event, but this is only temporary. we can go back to vote(event) when we switch to image buttons for each head

**Comment by mecathcart** [comment]
ok cool, just lemme know if you want me to do anything.  Also, I wrote a
post about shit people say on the blog, but i didn't post it yet (just
saved the draft).  I dunno, it didn't come out as good as I'd hoped, what
do you think?

On Tue, Feb 7, 2012 at 9:58 PM, cesine <
reply@reply.github.com
