### ISSUE TITLE
more time in between sentences

### ISSUE THREAD

**Issue by spirineta** [AccentsResearchLab/GamifyPsycholinguisticsExperiments#9]
We need a short interval of silence once a button has been pressed and before the next sentence is played.

**Comment by cesine** [comment]
can add a window.setTimeout() to delay the play.

**Comment by spirineta** [comment]
Two additional things: sometimes the sentences do not play from the beginning (they start from the 2nd or 3rd recorded word) and also I've had cases where two sentences were playing at the same time. Not sure why that might be.
